graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 142
         y 70
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 277
         y 70
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 275
         y 194
      ]
   ]
   node [
      id 3
      label "A"
      graphics [
         x 146
         y 192
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 146
         y 320
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 277
         y 320
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 400
         y 322
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 398
         y 194
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 398
         y 64
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 2
      label ""
      weight 1.0
   ]
]