graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "A"
      graphics [
         x 573
         y 321
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 496
         y 263
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 601
         y 239
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 586
         y 401
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 501
         y 183
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 398
         y 279
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 623
         y 162
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 721
         y 289
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 525
         y 474
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 696
         y 467
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 9
      label ""
      weight 1.0
   ]
]