graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 353
         y 151
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 417
         y 221
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 510
         y 152
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 359
         y 303
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 450
         y 338
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 519
         y 300
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 538
         y 392
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 512
         y 490
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 459
         y 405
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 445
         y 504
      ]
   ]
   node [
      id 12
      label "N"
      graphics [
         x 367
         y 518
      ]
   ]
   node [
      id 13
      label "N"
      graphics [
         x 402
         y 570
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 10
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 13
      label ""
      weight 1.0
   ]
]