graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 453
         y 275
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 538
         y 211
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 680
         y 222
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 756
         y 275
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 771
         y 370
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 704
         y 437
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 604
         y 449
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 524
         y 426
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 468
         y 368
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 0
      label ""
      weight 1.0
   ]
]