graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 349
         y 183
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 478
         y 183
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 583
         y 183
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 702
         y 183
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 702
         y 280
      ]
   ]
   node [
      id 7
      label "A"
      graphics [
         x 590
         y 280
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 477
         y 280
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 349
         y 280
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 349
         y 390
      ]
   ]
   node [
      id 12
      label "N"
      graphics [
         x 475
         y 390
      ]
   ]
   node [
      id 13
      label "N"
      graphics [
         x 592
         y 390
      ]
   ]
   node [
      id 14
      label "N"
      graphics [
         x 702
         y 390
      ]
   ]
   node [
      id 15
      label "N"
      graphics [
         x 702
         y 485
      ]
   ]
   node [
      id 17
      label "N"
      graphics [
         x 596
         y 485
      ]
   ]
   node [
      id 18
      label "N"
      graphics [
         x 478
         y 485
      ]
   ]
   node [
      id 19
      label "N"
      graphics [
         x 349
         y 485
      ]
   ]
   node [
      id 29
      label "N"
      graphics [
         x 923
         y 200
      ]
   ]
   node [
      id 30
      label "A"
      graphics [
         x 1059
         y 202
      ]
   ]
   node [
      id 31
      label "N"
      graphics [
         x 1202
         y 204
      ]
   ]
   node [
      id 32
      label "N"
      graphics [
         x 1353
         y 208
      ]
   ]
   node [
      id 33
      label "N"
      graphics [
         x 1503
         y 213
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 14
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 15
      label ""
      weight 1.0
   ]
   edge [
      source 15
      target 17
      label ""
      weight 1.0
   ]
   edge [
      source 17
      target 18
      label ""
      weight 1.0
   ]
   edge [
      source 18
      target 19
      label ""
      weight 1.0
   ]
   edge [
      source 19
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 18
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 17
      label ""
      weight 1.0
   ]
   edge [
      source 29
      target 30
      label ""
      weight 1.0
   ]
   edge [
      source 30
      target 31
      label ""
      weight 1.0
   ]
   edge [
      source 31
      target 32
      label ""
      weight 1.0
   ]
   edge [
      source 32
      target 33
      label ""
      weight 1.0
   ]
]